name: rtl

outputs:
  - design.v
  - design.vcs.v

commands:
  - cat ChalShiftReg.v puf.v BR32.v BR64.v BR128.v puf_super.v > outputs/design.v 
  - cat ChalShiftReg.v puf.v BR32.v BR64.v BR128.v puf_super.v > outputs/design.vcs.v 
