/*
###############################################################
#  Generated by:      Cadence Innovus 20.13-s083_1
#  OS:                Linux x86_64(Host ID iron-502-26)
#  Generated on:      Fri Jul  1 13:20:40 2022
#  Design:            puf_super
#  Command:           saveNetlist -includePowerGround -excludeLeafCell results/puf_super.vcs.pg.v
###############################################################
*/
module puf_super_ChalShiftReg_0 (
	clk, 
	si, 
	rstn, 
	c, 
	so, 
	FE_OFN0_c_113, 
	FE_OFN1_c_107, 
	FE_OFN2_c_91, 
	FE_OFN3_c_76, 
	FE_OFN4_c_74, 
	FE_OFN5_c_59, 
	FE_OFN7_c_58, 
	FE_OFN11_c_55, 
	FE_OFN13_c_54, 
	FE_OFN16_c_52, 
	FE_OFN18_c_51, 
	FE_OFN20_c_50, 
	FE_OFN24_c_47, 
	FE_OFN31_c_41, 
	FE_OFN36_c_36, 
	FE_OFN38_c_35, 
	FE_OFN41_c_32, 
	FE_OFN43_c_31, 
	FE_OFN46_c_29, 
	FE_OFN48_c_25, 
	FE_OFN51_c_22, 
	FE_OFN53_c_20, 
	FE_OFN59_c_14, 
	FE_OFN75_c_1, 
	FE_OFN77_c_82, 
	FE_OFN78_c_83, 
	FE_OFN79_c_85, 
	FE_OFN80_c_80, 
	FE_OFN81_c_77, 
	FE_OFN82_c_115, 
	vccd1, 
	vssd1);
   input clk;
   input si;
   input rstn;
   output [127:0] c;
   output so;
   output FE_OFN0_c_113;
   output FE_OFN1_c_107;
   output FE_OFN2_c_91;
   output FE_OFN3_c_76;
   output FE_OFN4_c_74;
   output FE_OFN5_c_59;
   output FE_OFN7_c_58;
   output FE_OFN11_c_55;
   output FE_OFN13_c_54;
   output FE_OFN16_c_52;
   output FE_OFN18_c_51;
   output FE_OFN20_c_50;
   output FE_OFN24_c_47;
   output FE_OFN31_c_41;
   output FE_OFN36_c_36;
   output FE_OFN38_c_35;
   output FE_OFN41_c_32;
   output FE_OFN43_c_31;
   output FE_OFN46_c_29;
   output FE_OFN48_c_25;
   output FE_OFN51_c_22;
   output FE_OFN53_c_20;
   output FE_OFN59_c_14;
   output FE_OFN75_c_1;
   output FE_OFN77_c_82;
   output FE_OFN78_c_83;
   output FE_OFN79_c_85;
   output FE_OFN80_c_80;
   output FE_OFN81_c_77;
   output FE_OFN82_c_115;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire FE_RN_6;
   wire FE_RN_5;
   wire FE_OFN0_FE_OFN184_c_115;
   wire CTS_12;
   wire CTS_11;
   wire CTS_9;
   wire CTS_10;
   wire CTS_8;
   wire CTS_5;
   wire CTS_4;
   wire CTS_7;
   wire CTS_6;
   wire CTS_1;
   wire CTS_3;
   wire CTS_2;
   wire FE_OFN188_c_119;
   wire FE_OFN187_c_122;
   wire FE_OFN186_c_118;
   wire FE_OFN185_c_112;
   wire FE_OFN182_c_19;
   wire FE_OFN180_c_69;
   wire FE_OFN179_c_71;
   wire FE_OFN178_c_70;
   wire FE_RN_4;
   wire FE_OFN174_FE_OFN35_c_91;
   wire FE_OFN173_c_72;
   wire FE_OFN172_c_73;
   wire FE_OFN171_c_90;
   wire FE_RN_3;
   wire FE_OFN169_FE_OFN52_c_74;
   wire FE_OFN168_c_89;
   wire FE_OFN166_c_88;
   wire FE_OFN165_c_75;
   wire FE_RN_2;
   wire FE_OFN149_c_0;
   wire FE_OFN142_c_4;
   wire FE_OFN139_c_6;
   wire FE_OFN138_c_7;
   wire FE_OFN137_c_8;
   wire FE_OFN136_c_9;
   wire FE_OFN135_c_10;
   wire FE_OFN134_c_11;
   wire FE_OFN107_c_24;
   wire FE_OFN105_c_26;
   wire FE_OFN104_c_27;
   wire FE_OFN103_c_28;
   wire FE_RN_1;
   wire FE_OFN1_rstn;
   wire FE_OFN0_rstn;

   assign c[127] = FE_RN_1 ;
   assign FE_OFN3_c_76 = FE_RN_2 ;
   assign FE_OFN4_c_74 = FE_RN_3 ;
   assign FE_RN_4 = c[91] ;
   assign FE_RN_6 = c[113] ;
   assign FE_RN_5 = c[115] ;

   // Module instantiations
   sky130_fd_sc_hd__clkbuf_4 FE_OFC0_FE_OFN184_c_115 (
	.A(FE_OFN0_FE_OFN184_c_115),
	.X(c[115]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00037 (
	.A(CTS_9),
	.Y(CTS_10), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00035 (
	.A(CTS_9),
	.Y(CTS_8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00048 (
	.A(CTS_11),
	.Y(CTS_9), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00031 (
	.A(CTS_5),
	.Y(CTS_4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00027 (
	.A(CTS_5),
	.Y(CTS_7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00025 (
	.A(CTS_5),
	.Y(CTS_6), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00046 (
	.A(CTS_11),
	.Y(CTS_5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00033 (
	.A(CTS_1),
	.Y(CTS_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00029 (
	.A(CTS_1),
	.Y(CTS_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00044 (
	.A(CTS_11),
	.Y(CTS_1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00062 (
	.A(CTS_12),
	.Y(CTS_11), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 CTS_ccl_inv_00065 (
	.A(clk),
	.Y(CTS_12), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC186_c_119 (
	.A(FE_OFN188_c_119),
	.X(c[119]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC185_c_122 (
	.A(FE_OFN187_c_122),
	.X(c[122]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC184_c_118 (
	.A(FE_OFN186_c_118),
	.X(c[118]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC183_c_112 (
	.A(FE_OFN185_c_112),
	.X(c[112]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC180_c_19 (
	.A(FE_OFN182_c_19),
	.X(c[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC178_c_69 (
	.A(FE_OFN180_c_69),
	.X(c[69]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC177_c_71 (
	.A(FE_OFN179_c_71),
	.X(c[71]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC176_c_70 (
	.A(FE_OFN178_c_70),
	.X(c[70]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC173_FE_OFN35_c_91 (
	.A(FE_OFN174_FE_OFN35_c_91),
	.X(c[91]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC172_c_72 (
	.A(FE_OFN173_c_72),
	.X(c[72]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC171_c_73 (
	.A(FE_OFN172_c_73),
	.X(c[73]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC170_c_90 (
	.A(FE_OFN171_c_90),
	.X(c[90]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC169_FE_OFN52_c_74 (
	.A(FE_OFN169_FE_OFN52_c_74),
	.X(FE_RN_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC168_c_89 (
	.A(FE_OFN168_c_89),
	.X(c[89]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC166_c_88 (
	.A(FE_OFN166_c_88),
	.X(c[88]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC165_c_75 (
	.A(FE_OFN165_c_75),
	.X(c[75]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC161_c_77 (
	.A(c[77]),
	.X(FE_OFN81_c_77), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC159_c_80 (
	.A(c[80]),
	.X(FE_OFN80_c_80), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC158_c_85 (
	.A(c[85]),
	.X(FE_OFN79_c_85), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC156_c_83 (
	.A(c[83]),
	.X(FE_OFN78_c_83), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC154_c_82 (
	.A(c[82]),
	.X(FE_OFN77_c_82), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC149_c_0 (
	.A(FE_OFN149_c_0),
	.X(c[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC147_c_1 (
	.A(c[1]),
	.X(FE_OFN75_c_1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC142_c_4 (
	.A(FE_OFN142_c_4),
	.X(c[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC139_c_6 (
	.A(FE_OFN139_c_6),
	.X(c[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC138_c_7 (
	.A(FE_OFN138_c_7),
	.X(c[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC137_c_8 (
	.A(FE_OFN137_c_8),
	.X(c[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC136_c_9 (
	.A(FE_OFN136_c_9),
	.X(c[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC135_c_10 (
	.A(FE_OFN135_c_10),
	.X(c[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC134_c_11 (
	.A(FE_OFN134_c_11),
	.X(c[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC126_c_14 (
	.A(c[14]),
	.X(FE_OFN59_c_14), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC114_c_20 (
	.A(c[20]),
	.X(FE_OFN53_c_20), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC110_c_22 (
	.A(c[22]),
	.X(FE_OFN51_c_22), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC107_c_24 (
	.A(FE_OFN107_c_24),
	.X(c[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC106_c_25 (
	.A(c[25]),
	.X(FE_OFN48_c_25), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC105_c_26 (
	.A(FE_OFN105_c_26),
	.X(c[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC104_c_27 (
	.A(FE_OFN104_c_27),
	.X(c[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC103_c_28 (
	.A(FE_OFN103_c_28),
	.X(c[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC102_c_29 (
	.A(c[29]),
	.X(FE_OFN46_c_29), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC98_c_31 (
	.A(c[31]),
	.X(FE_OFN43_c_31), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC97_c_32 (
	.A(c[32]),
	.X(FE_OFN41_c_32), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC94_c_35 (
	.A(c[35]),
	.X(FE_OFN38_c_35), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC93_c_36 (
	.A(c[36]),
	.X(FE_OFN36_c_36), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC88_c_41 (
	.A(c[41]),
	.X(FE_OFN31_c_41), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC80_c_47 (
	.A(c[47]),
	.X(FE_OFN24_c_47), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC76_c_50 (
	.A(c[50]),
	.X(FE_OFN20_c_50), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC75_c_51 (
	.A(c[51]),
	.X(FE_OFN18_c_51), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC74_c_52 (
	.A(c[52]),
	.X(FE_OFN16_c_52), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC72_c_54 (
	.A(c[54]),
	.X(FE_OFN13_c_54), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC71_c_55 (
	.A(c[55]),
	.X(FE_OFN11_c_55), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC68_c_58 (
	.A(c[58]),
	.X(FE_OFN7_c_58), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC67_c_59 (
	.A(c[59]),
	.X(FE_OFN5_c_59), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC19_c_107 (
	.A(c[107]),
	.X(FE_OFN1_c_107), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC1_rstn (
	.A(FE_OFN0_rstn),
	.X(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC0_rstn (
	.A(rstn),
	.X(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_0_ (
	.CLK(CTS_2),
	.D(si),
	.Q(FE_OFN149_c_0),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_1_ (
	.CLK(CTS_2),
	.D(c[0]),
	.Q(c[1]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_2_ (
	.CLK(CTS_10),
	.D(FE_OFN75_c_1),
	.Q(c[2]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_3_ (
	.CLK(CTS_10),
	.D(c[2]),
	.Q(c[3]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_4_ (
	.CLK(CTS_2),
	.D(c[3]),
	.Q(FE_OFN142_c_4),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_5_ (
	.CLK(CTS_2),
	.D(c[4]),
	.Q(c[5]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_6_ (
	.CLK(CTS_2),
	.D(c[5]),
	.Q(FE_OFN139_c_6),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_7_ (
	.CLK(CTS_2),
	.D(c[6]),
	.Q(FE_OFN138_c_7),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_8_ (
	.CLK(CTS_2),
	.D(c[7]),
	.Q(FE_OFN137_c_8),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_9_ (
	.CLK(CTS_2),
	.D(c[8]),
	.Q(FE_OFN136_c_9),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_10_ (
	.CLK(CTS_7),
	.D(c[9]),
	.Q(FE_OFN135_c_10),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_11_ (
	.CLK(CTS_7),
	.D(c[10]),
	.Q(FE_OFN134_c_11),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_12_ (
	.CLK(CTS_4),
	.D(c[11]),
	.Q(c[12]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_13_ (
	.CLK(CTS_4),
	.D(c[12]),
	.Q(c[13]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_14_ (
	.CLK(CTS_7),
	.D(c[13]),
	.Q(c[14]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_15_ (
	.CLK(CTS_7),
	.D(FE_OFN59_c_14),
	.Q(c[15]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_16_ (
	.CLK(CTS_7),
	.D(c[15]),
	.Q(c[16]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_17_ (
	.CLK(CTS_2),
	.D(c[16]),
	.Q(c[17]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_18_ (
	.CLK(CTS_2),
	.D(c[17]),
	.Q(c[18]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_19_ (
	.CLK(CTS_2),
	.D(c[18]),
	.Q(FE_OFN182_c_19),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_20_ (
	.CLK(CTS_2),
	.D(c[19]),
	.Q(c[20]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_21_ (
	.CLK(CTS_7),
	.D(FE_OFN53_c_20),
	.Q(c[21]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_22_ (
	.CLK(CTS_2),
	.D(c[21]),
	.Q(c[22]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_23_ (
	.CLK(CTS_7),
	.D(FE_OFN51_c_22),
	.Q(c[23]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_24_ (
	.CLK(CTS_7),
	.D(c[23]),
	.Q(FE_OFN107_c_24),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_25_ (
	.CLK(CTS_7),
	.D(c[24]),
	.Q(c[25]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_26_ (
	.CLK(CTS_7),
	.D(FE_OFN48_c_25),
	.Q(FE_OFN105_c_26),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_27_ (
	.CLK(CTS_7),
	.D(c[26]),
	.Q(FE_OFN104_c_27),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_28_ (
	.CLK(CTS_7),
	.D(c[27]),
	.Q(FE_OFN103_c_28),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_29_ (
	.CLK(CTS_7),
	.D(c[28]),
	.Q(c[29]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_30_ (
	.CLK(CTS_7),
	.D(FE_OFN46_c_29),
	.Q(c[30]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_31_ (
	.CLK(CTS_4),
	.D(c[30]),
	.Q(c[31]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_32_ (
	.CLK(CTS_4),
	.D(FE_OFN43_c_31),
	.Q(c[32]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_33_ (
	.CLK(CTS_6),
	.D(FE_OFN41_c_32),
	.Q(c[33]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_34_ (
	.CLK(CTS_4),
	.D(c[33]),
	.Q(c[34]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_35_ (
	.CLK(CTS_6),
	.D(c[34]),
	.Q(c[35]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_36_ (
	.CLK(CTS_4),
	.D(FE_OFN38_c_35),
	.Q(c[36]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_37_ (
	.CLK(CTS_4),
	.D(FE_OFN36_c_36),
	.Q(c[37]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_38_ (
	.CLK(CTS_6),
	.D(c[37]),
	.Q(c[38]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_39_ (
	.CLK(CTS_4),
	.D(c[38]),
	.Q(c[39]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_40_ (
	.CLK(CTS_4),
	.D(c[39]),
	.Q(c[40]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_41_ (
	.CLK(CTS_4),
	.D(c[40]),
	.Q(c[41]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_42_ (
	.CLK(CTS_6),
	.D(FE_OFN31_c_41),
	.Q(c[42]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_43_ (
	.CLK(CTS_4),
	.D(c[42]),
	.Q(c[43]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_44_ (
	.CLK(CTS_4),
	.D(c[43]),
	.Q(c[44]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_45_ (
	.CLK(CTS_7),
	.D(c[44]),
	.Q(c[45]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_46_ (
	.CLK(CTS_7),
	.D(c[45]),
	.Q(c[46]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_47_ (
	.CLK(CTS_2),
	.D(c[46]),
	.Q(c[47]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_48_ (
	.CLK(CTS_3),
	.D(FE_OFN24_c_47),
	.Q(c[48]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_49_ (
	.CLK(CTS_3),
	.D(c[48]),
	.Q(c[49]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_50_ (
	.CLK(CTS_3),
	.D(c[49]),
	.Q(c[50]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_51_ (
	.CLK(CTS_3),
	.D(FE_OFN20_c_50),
	.Q(c[51]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_52_ (
	.CLK(CTS_10),
	.D(FE_OFN18_c_51),
	.Q(c[52]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_53_ (
	.CLK(CTS_3),
	.D(FE_OFN16_c_52),
	.Q(c[53]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_54_ (
	.CLK(CTS_3),
	.D(c[53]),
	.Q(c[54]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_55_ (
	.CLK(CTS_3),
	.D(FE_OFN13_c_54),
	.Q(c[55]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_56_ (
	.CLK(CTS_10),
	.D(FE_OFN11_c_55),
	.Q(c[56]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_57_ (
	.CLK(CTS_10),
	.D(c[56]),
	.Q(c[57]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_58_ (
	.CLK(CTS_10),
	.D(c[57]),
	.Q(c[58]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_59_ (
	.CLK(CTS_10),
	.D(FE_OFN7_c_58),
	.Q(c[59]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_60_ (
	.CLK(CTS_10),
	.D(FE_OFN5_c_59),
	.Q(c[60]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_61_ (
	.CLK(CTS_8),
	.D(c[60]),
	.Q(c[61]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_62_ (
	.CLK(CTS_10),
	.D(c[61]),
	.Q(c[62]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_63_ (
	.CLK(CTS_10),
	.D(c[62]),
	.Q(c[63]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_64_ (
	.CLK(CTS_8),
	.D(c[63]),
	.Q(c[64]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_65_ (
	.CLK(CTS_10),
	.D(c[64]),
	.Q(c[65]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_66_ (
	.CLK(CTS_10),
	.D(c[65]),
	.Q(c[66]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_67_ (
	.CLK(CTS_10),
	.D(c[66]),
	.Q(c[67]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_68_ (
	.CLK(CTS_10),
	.D(c[67]),
	.Q(c[68]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_69_ (
	.CLK(CTS_10),
	.D(c[68]),
	.Q(FE_OFN180_c_69),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_70_ (
	.CLK(CTS_10),
	.D(c[69]),
	.Q(FE_OFN178_c_70),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_71_ (
	.CLK(CTS_10),
	.D(c[70]),
	.Q(FE_OFN179_c_71),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_72_ (
	.CLK(CTS_3),
	.D(c[71]),
	.Q(FE_OFN173_c_72),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_73_ (
	.CLK(CTS_3),
	.D(c[72]),
	.Q(FE_OFN172_c_73),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_74_ (
	.CLK(CTS_3),
	.D(c[73]),
	.Q(FE_OFN169_FE_OFN52_c_74),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_75_ (
	.CLK(CTS_3),
	.D(FE_OFN4_c_74),
	.Q(FE_OFN165_c_75),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_76_ (
	.CLK(CTS_3),
	.D(c[75]),
	.Q(FE_RN_2),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_77_ (
	.CLK(CTS_3),
	.D(FE_OFN3_c_76),
	.Q(c[77]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_78_ (
	.CLK(CTS_2),
	.D(FE_OFN81_c_77),
	.Q(c[78]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_79_ (
	.CLK(CTS_3),
	.D(c[78]),
	.Q(c[79]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_80_ (
	.CLK(CTS_2),
	.D(c[79]),
	.Q(c[80]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_81_ (
	.CLK(CTS_2),
	.D(FE_OFN80_c_80),
	.Q(c[81]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_82_ (
	.CLK(CTS_2),
	.D(c[81]),
	.Q(c[82]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_83_ (
	.CLK(CTS_2),
	.D(FE_OFN77_c_82),
	.Q(c[83]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_84_ (
	.CLK(CTS_2),
	.D(FE_OFN78_c_83),
	.Q(c[84]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_85_ (
	.CLK(CTS_7),
	.D(c[84]),
	.Q(c[85]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_86_ (
	.CLK(CTS_7),
	.D(FE_OFN79_c_85),
	.Q(c[86]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_87_ (
	.CLK(CTS_7),
	.D(c[86]),
	.Q(c[87]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_88_ (
	.CLK(CTS_7),
	.D(c[87]),
	.Q(FE_OFN166_c_88),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_89_ (
	.CLK(CTS_7),
	.D(c[88]),
	.Q(FE_OFN168_c_89),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_90_ (
	.CLK(CTS_4),
	.D(c[89]),
	.Q(FE_OFN171_c_90),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_91_ (
	.CLK(CTS_7),
	.D(c[90]),
	.Q(FE_OFN174_FE_OFN35_c_91),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_92_ (
	.CLK(CTS_7),
	.D(FE_RN_4),
	.Q(c[92]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_93_ (
	.CLK(CTS_4),
	.D(c[92]),
	.Q(c[93]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_94_ (
	.CLK(CTS_4),
	.D(c[93]),
	.Q(c[94]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_95_ (
	.CLK(CTS_4),
	.D(c[94]),
	.Q(c[95]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_96_ (
	.CLK(CTS_6),
	.D(c[95]),
	.Q(c[96]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_97_ (
	.CLK(CTS_6),
	.D(c[96]),
	.Q(c[97]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_98_ (
	.CLK(CTS_6),
	.D(c[97]),
	.Q(c[98]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_99_ (
	.CLK(CTS_6),
	.D(c[98]),
	.Q(c[99]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_100_ (
	.CLK(CTS_6),
	.D(c[99]),
	.Q(c[100]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_101_ (
	.CLK(CTS_6),
	.D(c[100]),
	.Q(c[101]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_102_ (
	.CLK(CTS_6),
	.D(c[101]),
	.Q(c[102]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_103_ (
	.CLK(CTS_6),
	.D(c[102]),
	.Q(c[103]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_104_ (
	.CLK(CTS_6),
	.D(c[103]),
	.Q(c[104]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_105_ (
	.CLK(CTS_6),
	.D(c[104]),
	.Q(c[105]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_106_ (
	.CLK(CTS_6),
	.D(c[105]),
	.Q(c[106]),
	.RESET_B(rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_107_ (
	.CLK(CTS_6),
	.D(c[106]),
	.Q(c[107]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_108_ (
	.CLK(CTS_6),
	.D(FE_OFN1_c_107),
	.Q(c[108]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_109_ (
	.CLK(CTS_6),
	.D(c[108]),
	.Q(c[109]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_110_ (
	.CLK(CTS_4),
	.D(c[109]),
	.Q(c[110]),
	.RESET_B(FE_OFN0_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_111_ (
	.CLK(CTS_2),
	.D(c[110]),
	.Q(c[111]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_112_ (
	.CLK(CTS_8),
	.D(c[111]),
	.Q(FE_OFN185_c_112),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_113_ (
	.CLK(CTS_8),
	.D(c[112]),
	.Q(c[113]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_114_ (
	.CLK(CTS_8),
	.D(FE_RN_6),
	.Q(c[114]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_115_ (
	.CLK(CTS_8),
	.D(c[114]),
	.Q(FE_OFN0_FE_OFN184_c_115),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_116_ (
	.CLK(CTS_8),
	.D(FE_RN_5),
	.Q(c[116]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_117_ (
	.CLK(CTS_8),
	.D(c[116]),
	.Q(c[117]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_118_ (
	.CLK(CTS_8),
	.D(c[117]),
	.Q(FE_OFN186_c_118),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_119_ (
	.CLK(CTS_8),
	.D(c[118]),
	.Q(FE_OFN188_c_119),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_120_ (
	.CLK(CTS_8),
	.D(c[119]),
	.Q(c[120]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_121_ (
	.CLK(CTS_8),
	.D(c[120]),
	.Q(c[121]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_122_ (
	.CLK(CTS_8),
	.D(c[121]),
	.Q(FE_OFN187_c_122),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_123_ (
	.CLK(CTS_8),
	.D(c[122]),
	.Q(c[123]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_124_ (
	.CLK(CTS_8),
	.D(c[123]),
	.Q(c[124]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_125_ (
	.CLK(CTS_8),
	.D(c[124]),
	.Q(c[125]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_126_ (
	.CLK(CTS_8),
	.D(c[125]),
	.Q(c[126]),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfrtp_2 c_reg_127_ (
	.CLK(CTS_8),
	.D(c[126]),
	.Q(FE_RN_1),
	.RESET_B(FE_OFN1_rstn), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module puf_super_puf_0 (
	reset, 
	length, 
	c, 
	out, 
	FE_OFN62_c_14, 
	FE_OFN65_c_13, 
	FE_OFN70_c_12, 
	vccd1, 
	vssd1);
   input reset;
   input [1:0] length;
   input [127:0] c;
   output out;
   input FE_OFN62_c_14;
   input FE_OFN65_c_13;
   input FE_OFN70_c_12;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire FE_OFN12_c_126;
   wire FE_OFN10_c_114;
   wire FE_OFN9_c_124;
   wire FE_OFN8_c_121;
   wire FE_OFN7_c_123;
   wire FE_OFN5_FE_OFN13_c_113;
   wire FE_OFN4_c_125;
   wire FE_OFN2_c_120;
   wire FE_OFN191_c_14;
   wire FE_OFN181_c_66;
   wire FE_OFN177_c_67;
   wire FE_OFN176_c_68;
   wire out_32;
   wire out_64;
   wire out_128;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire [2:0] reset_in;

   // Module instantiations
   sky130_fd_sc_hd__diode_2 DIODE_2 (
	.DIODE(c[120]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_1 (
	.DIODE(c[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC10_c_126 (
	.A(c[126]),
	.X(FE_OFN12_c_126), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC8_c_114 (
	.A(c[114]),
	.X(FE_OFN10_c_114), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC7_c_124 (
	.A(c[124]),
	.X(FE_OFN9_c_124), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC6_c_121 (
	.A(c[121]),
	.X(FE_OFN8_c_121), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC5_c_123 (
	.A(c[123]),
	.X(FE_OFN7_c_123), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC4_FE_OFN13_c_113 (
	.A(c[113]),
	.X(FE_OFN5_FE_OFN13_c_113), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC3_c_125 (
	.A(c[125]),
	.X(FE_OFN4_c_125), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC1_c_120 (
	.A(c[120]),
	.X(FE_OFN2_c_120), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC189_c_14 (
	.A(c[14]),
	.X(FE_OFN191_c_14), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC179_c_66 (
	.A(c[66]),
	.X(FE_OFN181_c_66), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC175_c_67 (
	.A(c[67]),
	.X(FE_OFN177_c_67), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC174_c_68 (
	.A(c[68]),
	.X(FE_OFN176_c_68), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   BR32 BR32_inst (
	.RESET(reset_in[0]),
	.OUT(out_32),
	.C({ c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		FE_OFN191_c_14,
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   BR64 BR64_inst (
	.RESET(reset_in[1]),
	.OUT(out_64),
	.C({ c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		FE_OFN62_c_14,
		FE_OFN65_c_13,
		FE_OFN70_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   BR128 BR128_inst (
	.RESET(reset_in[2]),
	.OUT(out_128),
	.C({ c[127],
		FE_OFN12_c_126,
		FE_OFN4_c_125,
		FE_OFN9_c_124,
		FE_OFN7_c_123,
		c[122],
		FE_OFN8_c_121,
		FE_OFN2_c_120,
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		FE_OFN10_c_114,
		FE_OFN5_FE_OFN13_c_113,
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		c[84],
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		c[76],
		c[75],
		c[74],
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		FE_OFN176_c_68,
		FE_OFN177_c_67,
		FE_OFN181_c_66,
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		FE_OFN62_c_14,
		FE_OFN65_c_13,
		FE_OFN70_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   sky130_fd_sc_hd__nand2b_1 U2 (
	.A_N(reset),
	.B(length[1]),
	.Y(reset_in[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U3 (
	.A(length[1]),
	.B(reset),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U4 (
	.A(length[0]),
	.B(n1),
	.Y(reset_in[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U6 (
	.A(n1),
	.B(n5),
	.Y(reset_in[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U7 (
	.A1(length[0]),
	.A2(out_32),
	.B1(n5),
	.B2(out_64),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U8 (
	.A(length[1]),
	.B(out_128),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o21ai_1 U9 (
	.A1(n4),
	.A2(length[1]),
	.B1(n3),
	.Y(out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 U5 (
	.A(length[0]),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module puf_super_puf_1 (
	reset, 
	length, 
	c, 
	out, 
	FE_OFN45_c_31, 
	FE_OFN56_c_16, 
	FE_OFN58_c_15, 
	FE_OFN61_c_14, 
	FE_OFN64_c_13, 
	FE_OFN69_c_12, 
	FE_OFN72_c_5, 
	FE_OFN74_c_3, 
	vccd1, 
	vssd1);
   input reset;
   input [1:0] length;
   input [127:0] c;
   output out;
   input FE_OFN45_c_31;
   input FE_OFN56_c_16;
   input FE_OFN58_c_15;
   input FE_OFN61_c_14;
   input FE_OFN64_c_13;
   input FE_OFN69_c_12;
   input FE_OFN72_c_5;
   input FE_OFN74_c_3;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire out_32;
   wire out_64;
   wire out_128;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire [2:0] reset_in;

   // Module instantiations
   BR32 BR32_inst (
	.RESET(reset_in[0]),
	.OUT(out_32),
	.C({ c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		c[14],
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   BR64 BR64_inst (
	.RESET(reset_in[1]),
	.OUT(out_64),
	.C({ c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		FE_OFN45_c_31,
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		FE_OFN56_c_16,
		FE_OFN58_c_15,
		FE_OFN61_c_14,
		FE_OFN64_c_13,
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN72_c_5,
		c[4],
		FE_OFN74_c_3,
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   BR128 BR128_inst (
	.RESET(reset_in[2]),
	.OUT(out_128),
	.C({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		c[114],
		c[113],
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		c[84],
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		c[76],
		c[75],
		c[74],
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		FE_OFN45_c_31,
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		FE_OFN56_c_16,
		FE_OFN58_c_15,
		FE_OFN61_c_14,
		FE_OFN64_c_13,
		FE_OFN69_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN72_c_5,
		c[4],
		FE_OFN74_c_3,
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   sky130_fd_sc_hd__nand2b_1 U2 (
	.A_N(reset),
	.B(length[1]),
	.Y(reset_in[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U3 (
	.A(length[1]),
	.B(reset),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U4 (
	.A(length[0]),
	.B(n1),
	.Y(reset_in[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U6 (
	.A(n1),
	.B(n5),
	.Y(reset_in[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U7 (
	.A1(length[0]),
	.A2(out_32),
	.B1(n5),
	.B2(out_64),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U8 (
	.A(length[1]),
	.B(out_128),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o21ai_1 U9 (
	.A1(n4),
	.A2(length[1]),
	.B1(n3),
	.Y(out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 U5 (
	.A(length[0]),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module puf_super_npuf_0 (
	reset, 
	length, 
	c, 
	out, 
	FE_OFN6_c_59, 
	FE_OFN8_c_58, 
	FE_OFN9_c_57, 
	FE_OFN10_c_56, 
	FE_OFN12_c_55, 
	FE_OFN14_c_54, 
	FE_OFN15_c_53, 
	FE_OFN17_c_52, 
	FE_OFN19_c_51, 
	FE_OFN21_c_50, 
	FE_OFN22_c_49, 
	FE_OFN23_c_48, 
	FE_OFN25_c_47, 
	FE_OFN26_c_46, 
	FE_OFN27_c_45, 
	FE_OFN28_c_44, 
	FE_OFN29_c_43, 
	FE_OFN30_c_42, 
	FE_OFN32_c_41, 
	FE_OFN33_c_40, 
	FE_OFN34_c_39, 
	FE_OFN35_c_38, 
	FE_OFN37_c_36, 
	FE_OFN39_c_35, 
	FE_OFN40_c_34, 
	FE_OFN42_c_32, 
	FE_OFN44_c_31, 
	FE_OFN47_c_29, 
	FE_OFN49_c_25, 
	FE_OFN50_c_23, 
	FE_OFN52_c_22, 
	FE_OFN54_c_18, 
	FE_OFN55_c_17, 
	FE_OFN57_c_15, 
	FE_OFN60_c_14, 
	FE_OFN63_c_13, 
	FE_OFN67_c_12, 
	FE_OFN71_c_5, 
	FE_OFN73_c_3, 
	FE_OFN76_c_1, 
	FE_OFN83_c_18, 
	vccd1, 
	vssd1);
   input reset;
   input [1:0] length;
   input [127:0] c;
   output out;
   input FE_OFN6_c_59;
   input FE_OFN8_c_58;
   input FE_OFN9_c_57;
   input FE_OFN10_c_56;
   input FE_OFN12_c_55;
   input FE_OFN14_c_54;
   input FE_OFN15_c_53;
   input FE_OFN17_c_52;
   input FE_OFN19_c_51;
   input FE_OFN21_c_50;
   input FE_OFN22_c_49;
   input FE_OFN23_c_48;
   input FE_OFN25_c_47;
   input FE_OFN26_c_46;
   input FE_OFN27_c_45;
   input FE_OFN28_c_44;
   input FE_OFN29_c_43;
   input FE_OFN30_c_42;
   input FE_OFN32_c_41;
   input FE_OFN33_c_40;
   input FE_OFN34_c_39;
   input FE_OFN35_c_38;
   input FE_OFN37_c_36;
   input FE_OFN39_c_35;
   input FE_OFN40_c_34;
   input FE_OFN42_c_32;
   input FE_OFN44_c_31;
   input FE_OFN47_c_29;
   input FE_OFN49_c_25;
   input FE_OFN50_c_23;
   input FE_OFN52_c_22;
   input FE_OFN54_c_18;
   input FE_OFN55_c_17;
   input FE_OFN57_c_15;
   input FE_OFN60_c_14;
   input FE_OFN63_c_13;
   input FE_OFN67_c_12;
   input FE_OFN71_c_5;
   input FE_OFN73_c_3;
   input FE_OFN76_c_1;
   input FE_OFN83_c_18;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire out_32;
   wire out_64;
   wire out_128;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire [2:0] reset_in;

   // Module instantiations
   NBR32 NBR32_inst (
	.RESET(reset_in[0]),
	.OUT(out_32),
	.C({ c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		FE_OFN57_c_15,
		c[14],
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   NBR64 NBR64_inst (
	.RESET(reset_in[1]),
	.OUT(out_64),
	.C({ c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		FE_OFN23_c_48,
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		FE_OFN44_c_31,
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		FE_OFN57_c_15,
		FE_OFN60_c_14,
		FE_OFN63_c_13,
		FE_OFN67_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN71_c_5,
		c[4],
		FE_OFN73_c_3,
		c[2],
		FE_OFN76_c_1,
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   NBR128 NBR128_inst (
	.RESET(reset_in[2]),
	.OUT(out_128),
	.C({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		c[114],
		c[113],
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		c[84],
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		c[76],
		c[75],
		c[74],
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		FE_OFN6_c_59,
		FE_OFN8_c_58,
		FE_OFN9_c_57,
		FE_OFN10_c_56,
		FE_OFN12_c_55,
		FE_OFN14_c_54,
		FE_OFN15_c_53,
		FE_OFN17_c_52,
		FE_OFN19_c_51,
		FE_OFN21_c_50,
		FE_OFN22_c_49,
		c[48],
		FE_OFN25_c_47,
		FE_OFN26_c_46,
		FE_OFN27_c_45,
		FE_OFN28_c_44,
		FE_OFN29_c_43,
		FE_OFN30_c_42,
		FE_OFN32_c_41,
		FE_OFN33_c_40,
		FE_OFN34_c_39,
		FE_OFN35_c_38,
		c[37],
		FE_OFN37_c_36,
		FE_OFN39_c_35,
		FE_OFN40_c_34,
		c[33],
		FE_OFN42_c_32,
		c[31],
		c[30],
		FE_OFN47_c_29,
		c[28],
		c[27],
		c[26],
		FE_OFN49_c_25,
		c[24],
		FE_OFN50_c_23,
		FE_OFN52_c_22,
		c[21],
		c[20],
		c[19],
		FE_OFN83_c_18,
		c[17],
		c[16],
		c[15],
		FE_OFN60_c_14,
		FE_OFN63_c_13,
		FE_OFN67_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN71_c_5,
		c[4],
		FE_OFN73_c_3,
		c[2],
		FE_OFN76_c_1,
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   sky130_fd_sc_hd__nand2b_1 U2 (
	.A_N(reset),
	.B(length[1]),
	.Y(reset_in[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U3 (
	.A(length[1]),
	.B(reset),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U4 (
	.A(length[0]),
	.B(n1),
	.Y(reset_in[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U6 (
	.A(n1),
	.B(n5),
	.Y(reset_in[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U7 (
	.A1(length[0]),
	.A2(out_32),
	.B1(n5),
	.B2(out_64),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U8 (
	.A(length[1]),
	.B(out_128),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o21ai_2 U9 (
	.A1(n4),
	.A2(length[1]),
	.B1(n3),
	.Y(out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 U5 (
	.A(length[0]),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module puf_super_npuf_1 (
	reset, 
	length, 
	c, 
	out, 
	FE_OFN66_c_13, 
	FE_OFN68_c_12, 
	vccd1, 
	vssd1);
   input reset;
   input [1:0] length;
   input [127:0] c;
   output out;
   input FE_OFN66_c_13;
   input FE_OFN68_c_12;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire FE_OFN183_c_17;
   wire FE_OFN167_c_18;
   wire FE_OFN123_c_16;
   wire out_32;
   wire out_64;
   wire out_128;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire [2:0] reset_in;

   // Module instantiations
   sky130_fd_sc_hd__clkbuf_1 FE_OFC181_c_17 (
	.A(c[17]),
	.X(FE_OFN183_c_17), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC167_c_18 (
	.A(c[18]),
	.X(FE_OFN167_c_18), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC123_c_16 (
	.A(c[16]),
	.X(FE_OFN123_c_16), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   NBR32 NBR32_inst (
	.RESET(reset_in[0]),
	.OUT(out_32),
	.C({ c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		FE_OFN167_c_18,
		FE_OFN183_c_17,
		FE_OFN123_c_16,
		c[15],
		c[14],
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   NBR64 NBR64_inst (
	.RESET(reset_in[1]),
	.OUT(out_64),
	.C({ c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		FE_OFN167_c_18,
		FE_OFN183_c_17,
		FE_OFN123_c_16,
		c[15],
		c[14],
		FE_OFN66_c_13,
		FE_OFN68_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   NBR128 NBR128_inst (
	.RESET(reset_in[2]),
	.OUT(out_128),
	.C({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		c[114],
		c[113],
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		c[84],
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		c[76],
		c[75],
		c[74],
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		FE_OFN167_c_18,
		FE_OFN183_c_17,
		FE_OFN123_c_16,
		c[15],
		c[14],
		FE_OFN66_c_13,
		FE_OFN68_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }), 
	.VSS(vssd1), 
	.VDD(vccd1));
   sky130_fd_sc_hd__nand2b_1 U2 (
	.A_N(reset),
	.B(length[1]),
	.Y(reset_in[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U3 (
	.A(length[1]),
	.B(reset),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U4 (
	.A(length[0]),
	.B(n1),
	.Y(reset_in[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U6 (
	.A(n1),
	.B(n5),
	.Y(reset_in[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U7 (
	.A1(length[0]),
	.A2(out_32),
	.B1(n5),
	.B2(out_64),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U8 (
	.A(length[1]),
	.B(out_128),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o21ai_0 U9 (
	.A1(n4),
	.A2(length[1]),
	.B1(n3),
	.Y(out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 U5 (
	.A(length[0]),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module puf_super (
	reset, 
	clk, 
	si, 
	rstn, 
	puf_sel1, 
	puf_sel0, 
	length1, 
	length0, 
	out, 
	so, 
	vssd1, 
	vccd1);
   input reset;
   input clk;
   input si;
   input rstn;
   input puf_sel1;
   input puf_sel0;
   input length1;
   input length0;
   output out;
   output so;
   inout vssd1;
   inout vccd1;

   // Internal wires
   wire VSSE;
   wire VSSPST;
   wire VPW;
   wire VSS;
   wire VDDPE;
   wire VDDCE;
   wire POC;
   wire VDDPST;
   wire VNW;
   wire VDD;
   wire FE_OFN11_c_68;
   wire FE_OFN3_c_48;
   wire FE_OFN194_c_18;
   wire FE_OFN184_c_115;
   wire FE_OFN163_c_87;
   wire FE_OFN162_c_86;
   wire FE_OFN161_c_77;
   wire FE_OFN160_c_84;
   wire FE_OFN159_c_80;
   wire FE_OFN158_c_85;
   wire FE_OFN157_c_78;
   wire FE_OFN156_c_83;
   wire FE_OFN155_c_81;
   wire FE_OFN154_c_82;
   wire FE_OFN153_c_79;
   wire FE_OFN152_out;
   wire FE_OFN151_out_4;
   wire FE_OFN150_out_3;
   wire FE_OFN147_c_1;
   wire FE_OFN146_c_2;
   wire FE_OFN145_c_2;
   wire FE_OFN144_c_3;
   wire FE_OFN143_c_3;
   wire FE_OFN141_c_5;
   wire FE_OFN140_c_5;
   wire FE_OFN132_c_12;
   wire FE_OFN131_c_12;
   wire FE_OFN130_c_13;
   wire FE_OFN129_c_13;
   wire FE_OFN126_c_14;
   wire FE_OFN125_c_15;
   wire FE_OFN124_c_15;
   wire FE_OFN122_c_16;
   wire FE_OFN120_c_17;
   wire FE_OFN118_c_18;
   wire FE_OFN116_c_19;
   wire FE_OFN114_c_20;
   wire FE_OFN112_c_21;
   wire FE_OFN110_c_22;
   wire FE_OFN108_c_23;
   wire FE_OFN106_c_25;
   wire FE_OFN102_c_29;
   wire FE_OFN101_c_30;
   wire FE_OFN100_c_30;
   wire FE_OFN99_c_31;
   wire FE_OFN98_c_31;
   wire FE_OFN97_c_32;
   wire FE_OFN96_c_33;
   wire FE_OFN95_c_34;
   wire FE_OFN94_c_35;
   wire FE_OFN93_c_36;
   wire FE_OFN92_c_37;
   wire FE_OFN91_c_38;
   wire FE_OFN90_c_39;
   wire FE_OFN89_c_40;
   wire FE_OFN88_c_41;
   wire FE_OFN87_c_42;
   wire FE_OFN86_c_43;
   wire FE_OFN85_c_44;
   wire FE_OFN84_c_45;
   wire FE_OFN82_c_46;
   wire FE_OFN80_c_47;
   wire FE_OFN79_c_48;
   wire FE_OFN77_c_49;
   wire FE_OFN76_c_50;
   wire FE_OFN75_c_51;
   wire FE_OFN74_c_52;
   wire FE_OFN73_c_53;
   wire FE_OFN72_c_54;
   wire FE_OFN71_c_55;
   wire FE_OFN70_c_56;
   wire FE_OFN69_c_57;
   wire FE_OFN68_c_58;
   wire FE_OFN67_c_59;
   wire FE_OFN66_c_60;
   wire FE_OFN65_c_61;
   wire FE_OFN64_c_62;
   wire FE_OFN63_c_63;
   wire FE_OFN62_c_64;
   wire FE_OFN61_c_65;
   wire FE_OFN52_c_74;
   wire FE_OFN50_c_76;
   wire FE_OFN35_c_91;
   wire FE_OFN34_c_92;
   wire FE_OFN33_c_93;
   wire FE_OFN32_c_94;
   wire FE_OFN31_c_95;
   wire FE_OFN30_c_96;
   wire FE_OFN29_c_97;
   wire FE_OFN28_c_98;
   wire FE_OFN27_c_99;
   wire FE_OFN26_c_100;
   wire FE_OFN25_c_101;
   wire FE_OFN24_c_102;
   wire FE_OFN23_c_103;
   wire FE_OFN22_c_104;
   wire FE_OFN21_c_105;
   wire FE_OFN20_c_106;
   wire FE_OFN19_c_107;
   wire FE_OFN18_c_108;
   wire FE_OFN17_c_109;
   wire FE_OFN16_c_110;
   wire FE_OFN15_c_111;
   wire FE_OFN13_c_113;
   wire FE_OFN11_c_116;
   wire FE_OFN10_c_117;
   wire FE_OFN3_length0;
   wire FE_OFN2_length1;
   wire out_1;
   wire out_2;
   wire out_3;
   wire out_4;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire [3:0] reset_puf;
   wire [127:0] c;

   // Module instantiations
   sky130_fd_sc_hd__clkbuf_1 FE_OFC9_c_68 (
	.A(c[68]),
	.X(FE_OFN11_c_68), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC2_c_48 (
	.A(c[48]),
	.X(FE_OFN3_c_48), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC192_c_18 (
	.A(c[18]),
	.X(FE_OFN194_c_18), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC164_FE_OFN50_c_76 (
	.A(FE_OFN50_c_76),
	.X(c[76]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC163_c_87 (
	.A(c[87]),
	.X(FE_OFN163_c_87), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC162_c_86 (
	.A(c[86]),
	.X(FE_OFN162_c_86), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC160_c_84 (
	.A(c[84]),
	.X(FE_OFN160_c_84), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC157_c_78 (
	.A(c[78]),
	.X(FE_OFN157_c_78), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC155_c_81 (
	.A(c[81]),
	.X(FE_OFN155_c_81), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC153_c_79 (
	.A(c[79]),
	.X(FE_OFN153_c_79), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC152_out (
	.A(FE_OFN152_out),
	.X(out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC151_out_4 (
	.A(out_4),
	.X(FE_OFN151_out_4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_1 FE_OFC150_out_3 (
	.A(out_3),
	.X(FE_OFN150_out_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC146_c_2 (
	.A(FE_OFN145_c_2),
	.Y(FE_OFN146_c_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 FE_OFC145_c_2 (
	.A(c[2]),
	.Y(FE_OFN145_c_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC144_c_3 (
	.A(FE_OFN143_c_3),
	.Y(FE_OFN144_c_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 FE_OFC143_c_3 (
	.A(c[3]),
	.Y(FE_OFN143_c_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC141_c_5 (
	.A(FE_OFN140_c_5),
	.Y(FE_OFN141_c_5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 FE_OFC140_c_5 (
	.A(c[5]),
	.Y(FE_OFN140_c_5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC132_c_12 (
	.A(FE_OFN131_c_12),
	.Y(FE_OFN132_c_12), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 FE_OFC131_c_12 (
	.A(c[12]),
	.Y(FE_OFN131_c_12), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC130_c_13 (
	.A(c[13]),
	.X(FE_OFN130_c_13), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC129_c_13 (
	.A(c[13]),
	.X(FE_OFN129_c_13), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC125_c_15 (
	.A(c[15]),
	.X(FE_OFN125_c_15), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC124_c_15 (
	.A(c[15]),
	.X(FE_OFN124_c_15), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC122_c_16 (
	.A(c[16]),
	.X(FE_OFN122_c_16), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC120_c_17 (
	.A(c[17]),
	.X(FE_OFN120_c_17), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC118_c_18 (
	.A(FE_OFN194_c_18),
	.X(FE_OFN118_c_18), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC116_c_19 (
	.A(c[19]),
	.X(FE_OFN116_c_19), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC112_c_21 (
	.A(c[21]),
	.X(FE_OFN112_c_21), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC108_c_23 (
	.A(c[23]),
	.X(FE_OFN108_c_23), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC101_c_30 (
	.A(FE_OFN100_c_30),
	.Y(FE_OFN101_c_30), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 FE_OFC100_c_30 (
	.A(c[30]),
	.Y(FE_OFN100_c_30), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC99_c_31 (
	.A(c[31]),
	.X(FE_OFN99_c_31), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC96_c_33 (
	.A(c[33]),
	.X(FE_OFN96_c_33), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC95_c_34 (
	.A(c[34]),
	.X(FE_OFN95_c_34), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC92_c_37 (
	.A(c[37]),
	.X(FE_OFN92_c_37), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC91_c_38 (
	.A(c[38]),
	.X(FE_OFN91_c_38), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC90_c_39 (
	.A(c[39]),
	.X(FE_OFN90_c_39), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC89_c_40 (
	.A(c[40]),
	.X(FE_OFN89_c_40), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC87_c_42 (
	.A(c[42]),
	.X(FE_OFN87_c_42), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC86_c_43 (
	.A(c[43]),
	.X(FE_OFN86_c_43), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC85_c_44 (
	.A(c[44]),
	.X(FE_OFN85_c_44), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC84_c_45 (
	.A(c[45]),
	.X(FE_OFN84_c_45), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC82_c_46 (
	.A(c[46]),
	.X(FE_OFN82_c_46), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC79_c_48 (
	.A(FE_OFN3_c_48),
	.X(FE_OFN79_c_48), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC77_c_49 (
	.A(c[49]),
	.X(FE_OFN77_c_49), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC73_c_53 (
	.A(c[53]),
	.X(FE_OFN73_c_53), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC70_c_56 (
	.A(c[56]),
	.X(FE_OFN70_c_56), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC69_c_57 (
	.A(c[57]),
	.X(FE_OFN69_c_57), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC66_c_60 (
	.A(c[60]),
	.X(FE_OFN66_c_60), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC65_c_61 (
	.A(c[61]),
	.X(FE_OFN65_c_61), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC64_c_62 (
	.A(c[62]),
	.X(FE_OFN64_c_62), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC63_c_63 (
	.A(c[63]),
	.X(FE_OFN63_c_63), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC62_c_64 (
	.A(c[64]),
	.X(FE_OFN62_c_64), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC61_c_65 (
	.A(c[65]),
	.X(FE_OFN61_c_65), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC34_c_92 (
	.A(c[92]),
	.X(FE_OFN34_c_92), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC33_c_93 (
	.A(c[93]),
	.X(FE_OFN33_c_93), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC32_c_94 (
	.A(c[94]),
	.X(FE_OFN32_c_94), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC31_c_95 (
	.A(c[95]),
	.X(FE_OFN31_c_95), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC30_c_96 (
	.A(c[96]),
	.X(FE_OFN30_c_96), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC29_c_97 (
	.A(c[97]),
	.X(FE_OFN29_c_97), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC28_c_98 (
	.A(c[98]),
	.X(FE_OFN28_c_98), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC27_c_99 (
	.A(c[99]),
	.X(FE_OFN27_c_99), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC26_c_100 (
	.A(c[100]),
	.X(FE_OFN26_c_100), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC25_c_101 (
	.A(c[101]),
	.X(FE_OFN25_c_101), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC24_c_102 (
	.A(c[102]),
	.X(FE_OFN24_c_102), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC23_c_103 (
	.A(c[103]),
	.X(FE_OFN23_c_103), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC22_c_104 (
	.A(c[104]),
	.X(FE_OFN22_c_104), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC21_c_105 (
	.A(c[105]),
	.X(FE_OFN21_c_105), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC20_c_106 (
	.A(c[106]),
	.X(FE_OFN20_c_106), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC18_c_108 (
	.A(c[108]),
	.X(FE_OFN18_c_108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC17_c_109 (
	.A(c[109]),
	.X(FE_OFN17_c_109), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC16_c_110 (
	.A(c[110]),
	.X(FE_OFN16_c_110), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC15_c_111 (
	.A(c[111]),
	.X(FE_OFN15_c_111), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC11_c_116 (
	.A(c[116]),
	.X(FE_OFN11_c_116), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC10_c_117 (
	.A(c[117]),
	.X(FE_OFN10_c_117), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_2 FE_OFC4_so (
	.A(c[127]),
	.X(so), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC3_length0 (
	.A(length0),
	.X(FE_OFN3_length0), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_4 FE_OFC2_length1 (
	.A(length1),
	.X(FE_OFN2_length1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   puf_super_ChalShiftReg_0 ChalShiftReg_inst (
	.clk(clk),
	.si(si),
	.rstn(rstn),
	.c({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		c[114],
		c[113],
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		c[84],
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		FE_UNCONNECTEDZ_0,
		c[75],
		c[74],
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		c[30],
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		c[14],
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		c[2],
		c[1],
		c[0] }),
	.FE_OFN0_c_113(FE_OFN13_c_113),
	.FE_OFN1_c_107(FE_OFN19_c_107),
	.FE_OFN2_c_91(FE_OFN35_c_91),
	.FE_OFN3_c_76(FE_OFN50_c_76),
	.FE_OFN4_c_74(FE_OFN52_c_74),
	.FE_OFN5_c_59(FE_OFN67_c_59),
	.FE_OFN7_c_58(FE_OFN68_c_58),
	.FE_OFN11_c_55(FE_OFN71_c_55),
	.FE_OFN13_c_54(FE_OFN72_c_54),
	.FE_OFN16_c_52(FE_OFN74_c_52),
	.FE_OFN18_c_51(FE_OFN75_c_51),
	.FE_OFN20_c_50(FE_OFN76_c_50),
	.FE_OFN24_c_47(FE_OFN80_c_47),
	.FE_OFN31_c_41(FE_OFN88_c_41),
	.FE_OFN36_c_36(FE_OFN93_c_36),
	.FE_OFN38_c_35(FE_OFN94_c_35),
	.FE_OFN41_c_32(FE_OFN97_c_32),
	.FE_OFN43_c_31(FE_OFN98_c_31),
	.FE_OFN46_c_29(FE_OFN102_c_29),
	.FE_OFN48_c_25(FE_OFN106_c_25),
	.FE_OFN51_c_22(FE_OFN110_c_22),
	.FE_OFN53_c_20(FE_OFN114_c_20),
	.FE_OFN59_c_14(FE_OFN126_c_14),
	.FE_OFN75_c_1(FE_OFN147_c_1),
	.FE_OFN77_c_82(FE_OFN154_c_82),
	.FE_OFN78_c_83(FE_OFN156_c_83),
	.FE_OFN79_c_85(FE_OFN158_c_85),
	.FE_OFN80_c_80(FE_OFN159_c_80),
	.FE_OFN81_c_77(FE_OFN161_c_77),
	.FE_OFN82_c_115(FE_OFN184_c_115), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   puf_super_puf_0 puf1_inst (
	.reset(reset_puf[0]),
	.length({ FE_OFN2_length1,
		FE_OFN3_length0 }),
	.c({ so,
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		FE_OFN10_c_117,
		FE_OFN11_c_116,
		c[115],
		c[114],
		c[113],
		c[112],
		FE_OFN15_c_111,
		FE_OFN16_c_110,
		FE_OFN17_c_109,
		FE_OFN18_c_108,
		FE_OFN19_c_107,
		FE_OFN20_c_106,
		FE_OFN21_c_105,
		FE_OFN22_c_104,
		FE_OFN23_c_103,
		FE_OFN24_c_102,
		FE_OFN25_c_101,
		FE_OFN26_c_100,
		FE_OFN27_c_99,
		FE_OFN28_c_98,
		FE_OFN29_c_97,
		FE_OFN30_c_96,
		FE_OFN31_c_95,
		FE_OFN32_c_94,
		FE_OFN33_c_93,
		FE_OFN34_c_92,
		c[91],
		c[90],
		c[89],
		c[88],
		FE_OFN163_c_87,
		FE_OFN162_c_86,
		FE_OFN158_c_85,
		FE_OFN160_c_84,
		FE_OFN156_c_83,
		FE_OFN154_c_82,
		FE_OFN155_c_81,
		FE_OFN159_c_80,
		FE_OFN153_c_79,
		FE_OFN157_c_78,
		FE_OFN161_c_77,
		c[76],
		c[75],
		FE_OFN52_c_74,
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		FE_OFN11_c_68,
		c[67],
		c[66],
		FE_OFN61_c_65,
		FE_OFN62_c_64,
		FE_OFN63_c_63,
		FE_OFN64_c_62,
		FE_OFN65_c_61,
		FE_OFN66_c_60,
		FE_OFN67_c_59,
		FE_OFN68_c_58,
		FE_OFN69_c_57,
		FE_OFN70_c_56,
		FE_OFN71_c_55,
		FE_OFN72_c_54,
		FE_OFN73_c_53,
		FE_OFN74_c_52,
		FE_OFN75_c_51,
		FE_OFN76_c_50,
		FE_OFN77_c_49,
		FE_OFN79_c_48,
		FE_OFN80_c_47,
		FE_OFN82_c_46,
		FE_OFN84_c_45,
		FE_OFN85_c_44,
		FE_OFN86_c_43,
		FE_OFN87_c_42,
		FE_OFN88_c_41,
		FE_OFN89_c_40,
		FE_OFN90_c_39,
		FE_OFN91_c_38,
		FE_OFN92_c_37,
		FE_OFN93_c_36,
		FE_OFN94_c_35,
		FE_OFN95_c_34,
		FE_OFN96_c_33,
		FE_OFN97_c_32,
		FE_OFN99_c_31,
		FE_OFN101_c_30,
		FE_OFN102_c_29,
		c[28],
		c[27],
		c[26],
		FE_OFN106_c_25,
		c[24],
		FE_OFN108_c_23,
		FE_OFN110_c_22,
		FE_OFN112_c_21,
		FE_OFN114_c_20,
		FE_OFN116_c_19,
		FE_OFN118_c_18,
		FE_OFN120_c_17,
		FE_OFN122_c_16,
		FE_OFN125_c_15,
		c[14],
		FE_OFN129_c_13,
		FE_OFN132_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN141_c_5,
		c[4],
		FE_OFN144_c_3,
		FE_OFN146_c_2,
		FE_OFN147_c_1,
		c[0] }),
	.out(out_1),
	.FE_OFN62_c_14(FE_OFN126_c_14),
	.FE_OFN65_c_13(FE_OFN130_c_13),
	.FE_OFN70_c_12(FE_OFN132_c_12), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   puf_super_puf_1 puf2_inst (
	.reset(reset_puf[1]),
	.length({ FE_OFN2_length1,
		FE_OFN3_length0 }),
	.c({ so,
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		FE_OFN10_c_117,
		FE_OFN11_c_116,
		c[115],
		c[114],
		c[113],
		c[112],
		FE_OFN15_c_111,
		FE_OFN16_c_110,
		FE_OFN17_c_109,
		FE_OFN18_c_108,
		FE_OFN19_c_107,
		FE_OFN20_c_106,
		FE_OFN21_c_105,
		FE_OFN22_c_104,
		FE_OFN23_c_103,
		FE_OFN24_c_102,
		FE_OFN25_c_101,
		FE_OFN26_c_100,
		FE_OFN27_c_99,
		FE_OFN28_c_98,
		FE_OFN29_c_97,
		FE_OFN30_c_96,
		FE_OFN31_c_95,
		FE_OFN32_c_94,
		FE_OFN33_c_93,
		FE_OFN34_c_92,
		c[91],
		c[90],
		c[89],
		c[88],
		FE_OFN163_c_87,
		FE_OFN162_c_86,
		FE_OFN158_c_85,
		FE_OFN160_c_84,
		FE_OFN156_c_83,
		FE_OFN154_c_82,
		FE_OFN155_c_81,
		FE_OFN159_c_80,
		FE_OFN153_c_79,
		FE_OFN157_c_78,
		FE_OFN161_c_77,
		c[76],
		c[75],
		FE_OFN52_c_74,
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		FE_OFN11_c_68,
		c[67],
		c[66],
		FE_OFN61_c_65,
		FE_OFN62_c_64,
		FE_OFN63_c_63,
		FE_OFN64_c_62,
		FE_OFN65_c_61,
		FE_OFN66_c_60,
		FE_OFN67_c_59,
		FE_OFN68_c_58,
		FE_OFN69_c_57,
		FE_OFN70_c_56,
		FE_OFN71_c_55,
		FE_OFN72_c_54,
		FE_OFN73_c_53,
		FE_OFN74_c_52,
		FE_OFN75_c_51,
		FE_OFN76_c_50,
		FE_OFN77_c_49,
		FE_OFN79_c_48,
		FE_OFN80_c_47,
		FE_OFN82_c_46,
		FE_OFN84_c_45,
		FE_OFN85_c_44,
		FE_OFN86_c_43,
		FE_OFN87_c_42,
		FE_OFN88_c_41,
		FE_OFN89_c_40,
		FE_OFN90_c_39,
		FE_OFN91_c_38,
		FE_OFN92_c_37,
		FE_OFN93_c_36,
		FE_OFN94_c_35,
		FE_OFN95_c_34,
		FE_OFN96_c_33,
		FE_OFN97_c_32,
		c[31],
		FE_OFN101_c_30,
		FE_OFN102_c_29,
		c[28],
		c[27],
		c[26],
		FE_OFN106_c_25,
		c[24],
		FE_OFN108_c_23,
		FE_OFN110_c_22,
		FE_OFN112_c_21,
		FE_OFN114_c_20,
		FE_OFN116_c_19,
		FE_OFN118_c_18,
		FE_OFN120_c_17,
		c[16],
		c[15],
		c[14],
		FE_OFN129_c_13,
		FE_OFN132_c_12,
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		FE_OFN146_c_2,
		FE_OFN147_c_1,
		c[0] }),
	.out(out_2),
	.FE_OFN45_c_31(FE_OFN99_c_31),
	.FE_OFN56_c_16(FE_OFN122_c_16),
	.FE_OFN58_c_15(FE_OFN125_c_15),
	.FE_OFN61_c_14(FE_OFN126_c_14),
	.FE_OFN64_c_13(FE_OFN130_c_13),
	.FE_OFN69_c_12(FE_OFN132_c_12),
	.FE_OFN72_c_5(FE_OFN141_c_5),
	.FE_OFN74_c_3(FE_OFN144_c_3), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   puf_super_npuf_0 puf3_inst (
	.reset(reset_puf[2]),
	.length({ FE_OFN2_length1,
		FE_OFN3_length0 }),
	.c({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		FE_OFN10_c_117,
		FE_OFN11_c_116,
		c[115],
		c[114],
		c[113],
		c[112],
		FE_OFN15_c_111,
		c[110],
		c[109],
		c[108],
		FE_OFN19_c_107,
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		FE_OFN163_c_87,
		FE_OFN162_c_86,
		FE_OFN158_c_85,
		FE_OFN160_c_84,
		FE_OFN156_c_83,
		FE_OFN154_c_82,
		FE_OFN155_c_81,
		FE_OFN159_c_80,
		FE_OFN153_c_79,
		FE_OFN157_c_78,
		FE_OFN161_c_77,
		c[76],
		c[75],
		FE_OFN52_c_74,
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		FE_OFN3_c_48,
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		FE_OFN92_c_37,
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		c[31],
		FE_OFN101_c_30,
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		c[15],
		c[14],
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		c[5],
		c[4],
		c[3],
		FE_OFN146_c_2,
		c[1],
		c[0] }),
	.out(out_3),
	.FE_OFN6_c_59(FE_OFN67_c_59),
	.FE_OFN8_c_58(FE_OFN68_c_58),
	.FE_OFN9_c_57(FE_OFN69_c_57),
	.FE_OFN10_c_56(FE_OFN70_c_56),
	.FE_OFN12_c_55(FE_OFN71_c_55),
	.FE_OFN14_c_54(FE_OFN72_c_54),
	.FE_OFN15_c_53(FE_OFN73_c_53),
	.FE_OFN17_c_52(FE_OFN74_c_52),
	.FE_OFN19_c_51(FE_OFN75_c_51),
	.FE_OFN21_c_50(FE_OFN76_c_50),
	.FE_OFN22_c_49(FE_OFN77_c_49),
	.FE_OFN23_c_48(c[48]),
	.FE_OFN25_c_47(FE_OFN80_c_47),
	.FE_OFN26_c_46(FE_OFN82_c_46),
	.FE_OFN27_c_45(FE_OFN84_c_45),
	.FE_OFN28_c_44(FE_OFN85_c_44),
	.FE_OFN29_c_43(FE_OFN86_c_43),
	.FE_OFN30_c_42(FE_OFN87_c_42),
	.FE_OFN32_c_41(FE_OFN88_c_41),
	.FE_OFN33_c_40(FE_OFN89_c_40),
	.FE_OFN34_c_39(FE_OFN90_c_39),
	.FE_OFN35_c_38(FE_OFN91_c_38),
	.FE_OFN37_c_36(FE_OFN93_c_36),
	.FE_OFN39_c_35(FE_OFN94_c_35),
	.FE_OFN40_c_34(FE_OFN95_c_34),
	.FE_OFN42_c_32(FE_OFN97_c_32),
	.FE_OFN44_c_31(FE_OFN98_c_31),
	.FE_OFN47_c_29(FE_OFN102_c_29),
	.FE_OFN49_c_25(FE_OFN106_c_25),
	.FE_OFN50_c_23(FE_OFN108_c_23),
	.FE_OFN52_c_22(FE_OFN110_c_22),
	.FE_OFN54_c_18(c[18]),
	.FE_OFN55_c_17(c[17]),
	.FE_OFN57_c_15(FE_OFN124_c_15),
	.FE_OFN60_c_14(FE_OFN126_c_14),
	.FE_OFN63_c_13(FE_OFN130_c_13),
	.FE_OFN67_c_12(FE_OFN132_c_12),
	.FE_OFN71_c_5(FE_OFN141_c_5),
	.FE_OFN73_c_3(FE_OFN144_c_3),
	.FE_OFN76_c_1(FE_OFN147_c_1),
	.FE_OFN83_c_18(FE_OFN194_c_18), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   puf_super_npuf_1 puf4_inst (
	.reset(reset_puf[3]),
	.length({ length1,
		length0 }),
	.c({ c[127],
		c[126],
		c[125],
		c[124],
		c[123],
		c[122],
		c[121],
		c[120],
		c[119],
		c[118],
		c[117],
		c[116],
		c[115],
		c[114],
		c[113],
		c[112],
		c[111],
		c[110],
		c[109],
		c[108],
		c[107],
		c[106],
		c[105],
		c[104],
		c[103],
		c[102],
		c[101],
		c[100],
		c[99],
		c[98],
		c[97],
		c[96],
		c[95],
		c[94],
		c[93],
		c[92],
		c[91],
		c[90],
		c[89],
		c[88],
		c[87],
		c[86],
		c[85],
		FE_OFN160_c_84,
		c[83],
		c[82],
		c[81],
		c[80],
		c[79],
		c[78],
		c[77],
		FE_OFN50_c_76,
		c[75],
		FE_OFN52_c_74,
		c[73],
		c[72],
		c[71],
		c[70],
		c[69],
		c[68],
		c[67],
		c[66],
		c[65],
		c[64],
		c[63],
		c[62],
		c[61],
		c[60],
		c[59],
		c[58],
		c[57],
		c[56],
		c[55],
		c[54],
		c[53],
		c[52],
		c[51],
		c[50],
		c[49],
		c[48],
		c[47],
		c[46],
		c[45],
		c[44],
		c[43],
		c[42],
		c[41],
		c[40],
		c[39],
		c[38],
		c[37],
		c[36],
		c[35],
		c[34],
		c[33],
		c[32],
		FE_OFN98_c_31,
		FE_OFN101_c_30,
		c[29],
		c[28],
		c[27],
		c[26],
		c[25],
		c[24],
		c[23],
		c[22],
		c[21],
		c[20],
		c[19],
		c[18],
		c[17],
		c[16],
		FE_OFN124_c_15,
		FE_OFN126_c_14,
		c[13],
		c[12],
		c[11],
		c[10],
		c[9],
		c[8],
		c[7],
		c[6],
		FE_OFN141_c_5,
		c[4],
		FE_OFN144_c_3,
		FE_OFN146_c_2,
		FE_OFN147_c_1,
		c[0] }),
	.out(out_4),
	.FE_OFN66_c_13(FE_OFN130_c_13),
	.FE_OFN68_c_12(FE_OFN132_c_12), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__clkinv_1 U13 (
	.A(puf_sel1),
	.Y(n11), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U14 (
	.A(reset),
	.B(n11),
	.Y(n7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_2 U15 (
	.A(puf_sel0),
	.B(n7),
	.Y(reset_puf[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_1 U16 (
	.A(puf_sel0),
	.Y(n9), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U17 (
	.A(n7),
	.B(n9),
	.Y(reset_puf[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U18 (
	.A(puf_sel1),
	.B(reset),
	.Y(n8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U19 (
	.A(puf_sel0),
	.B(n8),
	.Y(reset_puf[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U20 (
	.A(n8),
	.B(n9),
	.Y(reset_puf[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U21 (
	.A1(puf_sel0),
	.A2(out_1),
	.B1(n9),
	.B2(out_2),
	.Y(n12), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U22 (
	.A1(puf_sel0),
	.A2(FE_OFN150_out_3),
	.B1(n9),
	.B2(FE_OFN151_out_4),
	.Y(n10), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__o22ai_1 U23 (
	.A1(puf_sel1),
	.A2(n12),
	.B1(n11),
	.B2(n10),
	.Y(FE_OFN152_out), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

